# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: javaservice #  service name
spec:
  selector:
    app: java # app label
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: ClusterIP
